# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(508, 424)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(508, 424))
        MainWindow.setMaximumSize(QtCore.QSize(508, 424))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.frIVP = QtWidgets.QFrame(self.centralWidget)
        self.frIVP.setGeometry(QtCore.QRect(10, 10, 488, 126))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frIVP.sizePolicy().hasHeightForWidth())
        self.frIVP.setSizePolicy(sizePolicy)
        self.frIVP.setMinimumSize(QtCore.QSize(488, 126))
        self.frIVP.setMaximumSize(QtCore.QSize(488, 126))
        self.frIVP.setFrameShape(QtWidgets.QFrame.Box)
        self.frIVP.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frIVP.setObjectName("frIVP")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.frIVP)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 468, 106))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.layoutIVP = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.layoutIVP.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.layoutIVP.setContentsMargins(0, 0, 0, 0)
        self.layoutIVP.setObjectName("layoutIVP")
        self.lbEquation = QtWidgets.QLabel(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbEquation.sizePolicy().hasHeightForWidth())
        self.lbEquation.setSizePolicy(sizePolicy)
        self.lbEquation.setMinimumSize(QtCore.QSize(80, 30))
        self.lbEquation.setMaximumSize(QtCore.QSize(80, 0))
        self.lbEquation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbEquation.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbEquation.setTextFormat(QtCore.Qt.RichText)
        self.lbEquation.setScaledContents(False)
        self.lbEquation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbEquation.setObjectName("lbEquation")
        self.layoutIVP.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbEquation)
        self.editEquation = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editEquation.sizePolicy().hasHeightForWidth())
        self.editEquation.setSizePolicy(sizePolicy)
        self.editEquation.setMinimumSize(QtCore.QSize(380, 30))
        self.editEquation.setMaximumSize(QtCore.QSize(380, 30))
        self.editEquation.setStatusTip("")
        self.editEquation.setInputMask("")
        self.editEquation.setText("")
        self.editEquation.setClearButtonEnabled(True)
        self.editEquation.setObjectName("editEquation")
        self.layoutIVP.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editEquation)
        self.lbInitialCondition = QtWidgets.QLabel(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbInitialCondition.sizePolicy().hasHeightForWidth())
        self.lbInitialCondition.setSizePolicy(sizePolicy)
        self.lbInitialCondition.setMinimumSize(QtCore.QSize(80, 30))
        self.lbInitialCondition.setMaximumSize(QtCore.QSize(80, 30))
        self.lbInitialCondition.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbInitialCondition.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbInitialCondition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbInitialCondition.setObjectName("lbInitialCondition")
        self.layoutIVP.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbInitialCondition)
        self.editInitialCondition = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editInitialCondition.sizePolicy().hasHeightForWidth())
        self.editInitialCondition.setSizePolicy(sizePolicy)
        self.editInitialCondition.setMinimumSize(QtCore.QSize(80, 30))
        self.editInitialCondition.setMaximumSize(QtCore.QSize(80, 30))
        self.editInitialCondition.setStatusTip("")
        self.editInitialCondition.setInputMethodHints(QtCore.Qt.ImhExclusiveInputMask)
        self.editInitialCondition.setClearButtonEnabled(True)
        self.editInitialCondition.setObjectName("editInitialCondition")
        self.layoutIVP.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editInitialCondition)
        self.lbSolutionInterval = QtWidgets.QLabel(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbSolutionInterval.sizePolicy().hasHeightForWidth())
        self.lbSolutionInterval.setSizePolicy(sizePolicy)
        self.lbSolutionInterval.setMinimumSize(QtCore.QSize(80, 30))
        self.lbSolutionInterval.setMaximumSize(QtCore.QSize(80, 30))
        self.lbSolutionInterval.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbSolutionInterval.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbSolutionInterval.setObjectName("lbSolutionInterval")
        self.layoutIVP.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbSolutionInterval)
        self.layoutPoints = QtWidgets.QHBoxLayout()
        self.layoutPoints.setObjectName("layoutPoints")
        self.cbPoints = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.cbPoints.setMinimumSize(QtCore.QSize(80, 30))
        self.cbPoints.setMaximumSize(QtCore.QSize(80, 30))
        self.cbPoints.setObjectName("cbPoints")
        self.cbPoints.addItem("")
        self.cbPoints.addItem("")
        self.layoutPoints.addWidget(self.cbPoints)
        self.editSolutionInterval = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.editSolutionInterval.setEnabled(False)
        self.editSolutionInterval.setMinimumSize(QtCore.QSize(0, 30))
        self.editSolutionInterval.setMaximumSize(QtCore.QSize(16777215, 30))
        self.editSolutionInterval.setToolTip("")
        self.editSolutionInterval.setStatusTip("")
        self.editSolutionInterval.setClearButtonEnabled(False)
        self.editSolutionInterval.setObjectName("editSolutionInterval")
        self.layoutPoints.addWidget(self.editSolutionInterval)
        self.btnLoadFromFile = QtWidgets.QToolButton(self.formLayoutWidget_3)
        self.btnLoadFromFile.setMinimumSize(QtCore.QSize(30, 30))
        self.btnLoadFromFile.setMaximumSize(QtCore.QSize(30, 30))
        self.btnLoadFromFile.setCheckable(False)
        self.btnLoadFromFile.setChecked(False)
        self.btnLoadFromFile.setAutoRepeat(False)
        self.btnLoadFromFile.setObjectName("btnLoadFromFile")
        self.layoutPoints.addWidget(self.btnLoadFromFile)
        self.layoutIVP.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.layoutPoints)
        self.frRBNN = QtWidgets.QFrame(self.centralWidget)
        self.frRBNN.setGeometry(QtCore.QRect(10, 150, 488, 136))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frRBNN.sizePolicy().hasHeightForWidth())
        self.frRBNN.setSizePolicy(sizePolicy)
        self.frRBNN.setMinimumSize(QtCore.QSize(488, 136))
        self.frRBNN.setMaximumSize(QtCore.QSize(488, 136))
        self.frRBNN.setFrameShape(QtWidgets.QFrame.Box)
        self.frRBNN.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frRBNN.setObjectName("frRBNN")
        self.layoutWidget = QtWidgets.QWidget(self.frRBNN)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 10, 451, 114))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layoutRBNN = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.layoutRBNN.setContentsMargins(0, 0, 0, 0)
        self.layoutRBNN.setSpacing(6)
        self.layoutRBNN.setObjectName("layoutRBNN")
        self.layoutConfigSelect = QtWidgets.QVBoxLayout()
        self.layoutConfigSelect.setObjectName("layoutConfigSelect")
        self.layoutConfigCB = QtWidgets.QFormLayout()
        self.layoutConfigCB.setObjectName("layoutConfigCB")
        self.lbActivationFunction = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbActivationFunction.sizePolicy().hasHeightForWidth())
        self.lbActivationFunction.setSizePolicy(sizePolicy)
        self.lbActivationFunction.setMinimumSize(QtCore.QSize(0, 30))
        self.lbActivationFunction.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbActivationFunction.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbActivationFunction.setObjectName("lbActivationFunction")
        self.layoutConfigCB.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbActivationFunction)
        self.cbActivationFunction = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbActivationFunction.sizePolicy().hasHeightForWidth())
        self.cbActivationFunction.setSizePolicy(sizePolicy)
        self.cbActivationFunction.setMinimumSize(QtCore.QSize(94, 30))
        self.cbActivationFunction.setMaximumSize(QtCore.QSize(94, 30))
        self.cbActivationFunction.setStatusTip("")
        self.cbActivationFunction.setObjectName("cbActivationFunction")
        self.cbActivationFunction.addItem("")
        self.cbActivationFunction.addItem("")
        self.cbActivationFunction.addItem("")
        self.layoutConfigCB.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbActivationFunction)
        self.lbOptimizer = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOptimizer.sizePolicy().hasHeightForWidth())
        self.lbOptimizer.setSizePolicy(sizePolicy)
        self.lbOptimizer.setMinimumSize(QtCore.QSize(0, 30))
        self.lbOptimizer.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbOptimizer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbOptimizer.setObjectName("lbOptimizer")
        self.layoutConfigCB.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbOptimizer)
        self.cbOptimizer = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOptimizer.sizePolicy().hasHeightForWidth())
        self.cbOptimizer.setSizePolicy(sizePolicy)
        self.cbOptimizer.setMinimumSize(QtCore.QSize(94, 30))
        self.cbOptimizer.setMaximumSize(QtCore.QSize(94, 30))
        self.cbOptimizer.setStatusTip("")
        self.cbOptimizer.setObjectName("cbOptimizer")
        self.cbOptimizer.addItem("")
        self.cbOptimizer.addItem("")
        self.cbOptimizer.addItem("")
        self.layoutConfigCB.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbOptimizer)
        self.layoutConfigSelect.addLayout(self.layoutConfigCB)
        self.layoutRBNN.addLayout(self.layoutConfigSelect)
        self.layoutConfigEdit = QtWidgets.QFormLayout()
        self.layoutConfigEdit.setObjectName("layoutConfigEdit")
        self.lbIterations = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbIterations.sizePolicy().hasHeightForWidth())
        self.lbIterations.setSizePolicy(sizePolicy)
        self.lbIterations.setMinimumSize(QtCore.QSize(80, 30))
        self.lbIterations.setMaximumSize(QtCore.QSize(80, 30))
        self.lbIterations.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbIterations.setTextFormat(QtCore.Qt.AutoText)
        self.lbIterations.setObjectName("lbIterations")
        self.layoutConfigEdit.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbIterations)
        self.editIterations = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editIterations.sizePolicy().hasHeightForWidth())
        self.editIterations.setSizePolicy(sizePolicy)
        self.editIterations.setMinimumSize(QtCore.QSize(80, 30))
        self.editIterations.setMaximumSize(QtCore.QSize(80, 30))
        self.editIterations.setStatusTip("")
        self.editIterations.setClearButtonEnabled(True)
        self.editIterations.setObjectName("editIterations")
        self.layoutConfigEdit.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editIterations)
        self.lbNeurons = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbNeurons.sizePolicy().hasHeightForWidth())
        self.lbNeurons.setSizePolicy(sizePolicy)
        self.lbNeurons.setMinimumSize(QtCore.QSize(80, 30))
        self.lbNeurons.setMaximumSize(QtCore.QSize(80, 30))
        self.lbNeurons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbNeurons.setObjectName("lbNeurons")
        self.layoutConfigEdit.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbNeurons)
        self.lbAccuracy = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbAccuracy.sizePolicy().hasHeightForWidth())
        self.lbAccuracy.setSizePolicy(sizePolicy)
        self.lbAccuracy.setMinimumSize(QtCore.QSize(80, 30))
        self.lbAccuracy.setMaximumSize(QtCore.QSize(80, 30))
        self.lbAccuracy.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbAccuracy.setTextFormat(QtCore.Qt.AutoText)
        self.lbAccuracy.setObjectName("lbAccuracy")
        self.layoutConfigEdit.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbAccuracy)
        self.editAccuracy = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editAccuracy.sizePolicy().hasHeightForWidth())
        self.editAccuracy.setSizePolicy(sizePolicy)
        self.editAccuracy.setMinimumSize(QtCore.QSize(80, 30))
        self.editAccuracy.setMaximumSize(QtCore.QSize(80, 30))
        self.editAccuracy.setStatusTip("")
        self.editAccuracy.setClearButtonEnabled(True)
        self.editAccuracy.setObjectName("editAccuracy")
        self.layoutConfigEdit.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editAccuracy)
        self.editNeurons = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editNeurons.sizePolicy().hasHeightForWidth())
        self.editNeurons.setSizePolicy(sizePolicy)
        self.editNeurons.setMaximumSize(QtCore.QSize(80, 30))
        self.editNeurons.setMinimum(1)
        self.editNeurons.setMaximum(999999999)
        self.editNeurons.setObjectName("editNeurons")
        self.layoutConfigEdit.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editNeurons)
        self.layoutRBNN.addLayout(self.layoutConfigEdit)
        self.btnSolve = QtWidgets.QPushButton(self.centralWidget)
        self.btnSolve.setEnabled(False)
        self.btnSolve.setGeometry(QtCore.QRect(380, 340, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSolve.sizePolicy().hasHeightForWidth())
        self.btnSolve.setSizePolicy(sizePolicy)
        self.btnSolve.setMinimumSize(QtCore.QSize(120, 30))
        self.btnSolve.setMaximumSize(QtCore.QSize(120, 30))
        self.btnSolve.setObjectName("btnSolve")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(10, 300, 120, 65))
        self.frame.setMinimumSize(QtCore.QSize(120, 65))
        self.frame.setMaximumSize(QtCore.QSize(120, 65))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 132, 62))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbPlotSolution = QtWidgets.QCheckBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbPlotSolution.sizePolicy().hasHeightForWidth())
        self.cbPlotSolution.setSizePolicy(sizePolicy)
        self.cbPlotSolution.setMinimumSize(QtCore.QSize(0, 30))
        self.cbPlotSolution.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cbPlotSolution.setStatusTip("")
        self.cbPlotSolution.setChecked(True)
        self.cbPlotSolution.setTristate(False)
        self.cbPlotSolution.setObjectName("cbPlotSolution")
        self.verticalLayout.addWidget(self.cbPlotSolution)
        self.cbPlotLoss = QtWidgets.QCheckBox(self.layoutWidget1)
        self.cbPlotLoss.setStatusTip("")
        self.cbPlotLoss.setObjectName("cbPlotLoss")
        self.verticalLayout.addWidget(self.cbPlotLoss)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 508, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionProgram = QtWidgets.QAction(MainWindow)
        self.actionProgram.setObjectName("actionProgram")
        self.menuHelp.addAction(self.actionProgram)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.cbActivationFunction.setCurrentIndex(0)
        self.cbOptimizer.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RBNN"))
        self.lbEquation.setText(_translate("MainWindow", "dx/dt ="))
        self.editEquation.setToolTip(_translate("MainWindow", "f(x, t)"))
        self.editEquation.setPlaceholderText(_translate("MainWindow", "right side of the first order ode"))
        self.lbInitialCondition.setText(_translate("MainWindow", "t0,x0 ="))
        self.editInitialCondition.setToolTip(_translate("MainWindow", "initial condition"))
        self.editInitialCondition.setPlaceholderText(_translate("MainWindow", "t0, x0"))
        self.lbSolutionInterval.setText(_translate("MainWindow", "Read points  "))
        self.cbPoints.setToolTip(_translate("MainWindow", "from where to load interval solution"))
        self.cbPoints.setItemText(0, _translate("MainWindow", "from file"))
        self.cbPoints.setItemText(1, _translate("MainWindow", "direct"))
        self.editSolutionInterval.setPlaceholderText(_translate("MainWindow", "[x0, x1, x2,..., xN]"))
        self.btnLoadFromFile.setToolTip(_translate("MainWindow", "load interval from file"))
        self.btnLoadFromFile.setText(_translate("MainWindow", "..."))
        self.lbActivationFunction.setText(_translate("MainWindow", "Activation Function:"))
        self.cbActivationFunction.setToolTip(_translate("MainWindow", "which activation function to use"))
        self.cbActivationFunction.setItemText(0, _translate("MainWindow", "sigmoid"))
        self.cbActivationFunction.setItemText(1, _translate("MainWindow", "tanh"))
        self.cbActivationFunction.setItemText(2, _translate("MainWindow", "relu"))
        self.lbOptimizer.setText(_translate("MainWindow", "Optimizer:"))
        self.cbOptimizer.setToolTip(_translate("MainWindow", "which optimization method to use"))
        self.cbOptimizer.setItemText(0, _translate("MainWindow", "rmsprop"))
        self.cbOptimizer.setItemText(1, _translate("MainWindow", "adam"))
        self.cbOptimizer.setItemText(2, _translate("MainWindow", "sgd"))
        self.lbIterations.setText(_translate("MainWindow", "Epochs:"))
        self.editIterations.setToolTip(_translate("MainWindow", "number of epochs of the training"))
        self.editIterations.setText(_translate("MainWindow", "1000"))
        self.editIterations.setPlaceholderText(_translate("MainWindow", "1000"))
        self.lbNeurons.setText(_translate("MainWindow", "Neurons: "))
        self.lbAccuracy.setText(_translate("MainWindow", "Accuracy:"))
        self.editAccuracy.setToolTip(_translate("MainWindow", "desired solution precision"))
        self.editAccuracy.setText(_translate("MainWindow", "1e-2"))
        self.editAccuracy.setPlaceholderText(_translate("MainWindow", "1e-2"))
        self.editNeurons.setToolTip(_translate("MainWindow", "number of neurons in the hidden layer (can\'t be greater than points in interval)"))
        self.btnSolve.setText(_translate("MainWindow", "Solve"))
        self.cbPlotSolution.setToolTip(_translate("MainWindow", "whatever to show a graphical solution or not"))
        self.cbPlotSolution.setText(_translate("MainWindow", "Plot Solution"))
        self.cbPlotLoss.setToolTip(_translate("MainWindow", "whatever to show the loss vs. epoch history or not"))
        self.cbPlotLoss.setText(_translate("MainWindow", "Plot Loss"))
        self.menuHelp.setTitle(_translate("MainWindow", "He&lp"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionProgram.setText(_translate("MainWindow", "&Program"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
